[programs.localnet]
hapi_core = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/dread/.config/solana/id.json"

[scripts]
test = "npx jest --verbose --detectOpenHandles"
