[package]
name = "hapi-contract"
authors = ["HAPI"]
version = "0.1.0"
edition = "2021"

readme = "README.md"
license = "GPL-3.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = { version = "4.1.1" }
near-contract-standards = "4.1.1"
