[package]
name = "hapi-core-near"
authors = ["HAPI"]
version = "0.1.0"
edition = "2021"

readme = "README.md"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = { version = "4.1.1" }
near-contract-standards = "4.1.1"
