log_level = "info"
is_json_logging = false
listener = "0.0.0.0:3001"

[indexer]
network = "near"
rpc_node_url =  "https://archival-rpc.testnet.near.org"
webhook_url = "http://localhost:8080"
contract_address = "sub_hapi.testcore.testnet"
state_file = "data/state.json"
