[package]
name = "hapi-core-cli"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]
name = "hapi_core"

[dependencies]
async-trait = "0.1"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
anyhow = { version = "1" }
clap = { version = "4", features = ["env"] }

# EVM dependencies
ethers = "2"
ethers-providers = "2"
ethers-signers = "2"
ethers-contract = "2"
