[package]
name = "hapi-core-cli"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]
name = "hapi_core"

[dependencies]
async-trait = "0.1.68"
ethers = "2.0.6"
ethers-providers = "2.0.6"
ethers-signers = "2.0.6"
