[package]
name = "hapi-explorer"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "entity", "migration"]

[dependencies]
axum = "0.6.20"

tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
    "fmt",
    "json",
    "env-filter",
] }

config = "0.13.4"
serde = { version = "1", features = ["derive"] }
serde_with = { version = "2.2.0", features = ["chrono"] }
serde_json = "1"
anyhow = "1"

metrics-exporter-prometheus = "0.12.1"
metrics = "0.21.1"


[dev-dependencies]
reqwest = "0.11.12"
